import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { UserContextProvider } from "./context/UserContext";

export const metadata: Metadata = {
  title: "Farrer Park Hospital",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ overflowY: "hidden" }}>
      <body className={GeistSans.className}>
        <UserContextProvider>{children}</UserContextProvider>
      </body>
    </html>
  );
}
