import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { UserContextProvider } from "@/app/context/UserContext";
import { LoadingProvider } from '@/app/context/LoadingContext';
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";


export const metadata: Metadata = {
  title: "Farrer Park Hospital",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ overflowY: "hidden" }}>
      <body className={GeistSans.className}>
        <LoadingProvider>
        <UserContextProvider>{children}</UserContextProvider>
        </LoadingProvider>
        <ToastContainer position="top-right" autoClose={5000} hideProgressBar />
      </body>
    </html>
  );
}
